In [ ]:
from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib as plt
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data_location = '/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/datasheet.zip'

In [ ]:
# !unzip '/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/datasheet.zip' -d '/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet'

In [ ]:
Data_Dictionary = pd.read_excel('/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/Data Dictionary.xlsx')

In [ ]:
train_df = pd.read_csv('/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/Train.csv')

<ipython-input-52-367124499>:1: DtypeWarning: Columns (13,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv('/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/Train.csv')

In [ ]:
train_df

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,1139246,66000,999089,3157,121,3.0,2004,68.0,Low,11/16/2006 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,1139248,57000,117657,77,121,3.0,1996,4640.0,Low,3/26/2004 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,High,2/26/2004 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,High,5/19/2011 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,Medium,7/23/2009 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,NaN,NaN,11/2/2011 0:00,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401121,6333337,11000,1830472,21439,149,1.0,2005,NaN,NaN,11/2/2011 0:00,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401122,6333338,11500,1887659,21439,149,1.0,2005,NaN,NaN,11/2/2011 0:00,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401123,6333341,9000,1903570,21435,149,2.0,2005,NaN,NaN,10/25/2011 0:00,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401124,6333342,7750,1926965,21435,149,2.0,2005,NaN,NaN,10/25/2011 0:00,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 53 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   SalePrice                 401125 non-null  int64
 2   MachineID                 401125 non-null  int64
 3   ModelID                   401125 non-null  int64
 4   datasource                401125 non-null  int64
 5   auctioneerID              380989 non-null  float64
 6   YearMade                  401125 non-null  int64
 7   MachineHoursCurrentMeter  142765 non-null  float64
 8   UsageBand                 69639 non-null   object
 9   saledate                  401125 non-null  object
 10  fiModelDesc               401125 non-null  object
 11  fiBaseModel               401125 non-null  object
 12  fiSecondaryDesc           263934 non-null  object
 13  fiModelSeries             56908 non-null   object
 14  fiModelDescriptor         71919 non-null   object
 15  ProductSize               190350 non-null  object
 16  fiProductClassDesc        401125 non-null  object
 17  state                     401125 non-null  object
 18  ProductGroup              401125 non-null  object
 19  ProductGroupDesc          401125 non-null  object
 20  Drive_System              104361 non-null  object
 21  Enclosure                 400800 non-null  object
 22  Forks                     192077 non-null  object
 23  Pad_Type                  79134 non-null   object
 24  Ride_Control              148606 non-null  object
 25  Stick                     79134 non-null   object
 26  Transmission              183230 non-null  object
 27  Turbocharged              79134 non-null   object
 28  Blade_Extension           25219 non-null   object
 29  Blade_Width               25219 non-null   object
 30  Enclosure_Type            25219 non-null   object
 31  Engine_Horsepower         25219 non-null   object
 32  Hydraulics                320570 non-null  object
 33  Pushblock                 25219 non-null   object
 34  Ripper                    104137 non-null  object
 35  Scarifier                 25230 non-null   object
 36  Tip_Control               25219 non-null   object
 37  Tire_Size                 94718 non-null   object
 38  Coupler                   213952 non-null  object
 39  Coupler_System            43458 non-null   object
 40  Grouser_Tracks            43362 non-null   object
 41  Hydraulics_Flow           43362 non-null   object
 42  Track_Type                99153 non-null   object
 43  Undercarriage_Pad_Width   99872 non-null   object
 44  Stick_Length              99218 non-null   object
 45  Thumb                     99288 non-null   object
 46  Pattern_Changer           99218 non-null   object
 47  Grouser_Type              99153 non-null   object
 48  Backhoe_Mounting          78672 non-null   object
 49  Blade_Type                79833 non-null   object
 50  Travel_Controls           79834 non-null   object
 51  Differential_Type         69411 non-null   object
 52  Steering_Controls         69369 non-null   object
dtypes: float64(2), int64(6), object(45)
memory usage: 162.2+ MB

In [ ]:
train_df = train_df.drop_duplicates()

In [ ]:
train_df.isnull().sum().sort_values(ascending=False)
null_columns = (train_df.isnull().sum())/len(train_df)*100
null_columns = null_columns.sort_values(ascending=False)
null_columns

Pushblock                   93.712932
Tip_Control                 93.712932
Enclosure_Type              93.712932
Engine_Horsepower           93.712932
Blade_Extension             93.712932
Blade_Width                 93.712932
Scarifier                   93.710190
Grouser_Tracks              89.189903
Hydraulics_Flow             89.189903
Coupler_System              89.165971
fiModelSeries               85.812901
Steering_Controls           82.706388
Differential_Type           82.695918
UsageBand                   82.639078
fiModelDescriptor           82.070676
Backhoe_Mounting            80.387161
Stick                       80.271985
Pad_Type                    80.271985
Turbocharged                80.271985
Blade_Type                  80.097725
Travel_Controls             80.097476
Tire_Size                   76.386912
Grouser_Type                75.281271
Track_Type                  75.281271
Stick_Length                75.265067
Pattern_Changer             75.265067
Thumb                       75.247616
Undercarriage_Pad_Width     75.102026
Ripper                      74.038766
Drive_System                73.982923
MachineHoursCurrentMeter    64.408850
Ride_Control                62.952696
Transmission                54.320972
ProductSize                 52.545964
Forks                       52.115425
Coupler                     46.662013
fiSecondaryDesc             34.201558
Hydraulics                  20.082269
auctioneerID                 5.019882
Enclosure                    0.081022
ProductGroupDesc             0.000000
YearMade                     0.000000
ProductGroup                 0.000000
state                        0.000000
fiProductClassDesc           0.000000
SalePrice                    0.000000
MachineID                    0.000000
ModelID                      0.000000
SalesID                      0.000000
datasource                   0.000000
saledate                     0.000000
fiModelDesc                  0.000000
fiBaseModel                  0.000000
dtype: float64

In [ ]:
train_df['saledate'] = pd.to_datetime(train_df['saledate'])
train_df

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,1139246,66000,999089,3157,121,3.0,2004,68.0,Low,2006-11-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,1139248,57000,117657,77,121,3.0,1996,4640.0,Low,2004-03-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,High,2004-02-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,High,2011-05-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,Medium,2009-07-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401121,6333337,11000,1830472,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401122,6333338,11500,1887659,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401123,6333341,9000,1903570,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401124,6333342,7750,1926965,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN

In [ ]:
train_df['saleYear'] = train_df['saledate'].dt.year
train_df

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls,saleYear
0,1139246,66000,999089,3157,121,3.0,2004,68.0,Low,2006-11-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional,2006
1,1139248,57000,117657,77,121,3.0,1996,4640.0,Low,2004-03-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional,2004
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,High,2004-02-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,High,2011-05-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,Medium,2009-07-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011
401121,6333337,11000,1830472,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011
401122,6333338,11500,1887659,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011
401123,6333341,9000,1903570,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011
401124,6333342,7750,1926965,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011

In [ ]:
train_df.drop('saledate', axis=1, inplace=True)
train_df

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,fiModelDesc,...,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls,saleYear
0,1139246,66000,999089,3157,121,3.0,2004,68.0,Low,521D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional,2006
1,1139248,57000,117657,77,121,3.0,1996,4640.0,Low,950FII,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional,2004
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,High,226,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,High,PC120-6E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,Medium,S175,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,NaN,NaN,35NX2,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011
401121,6333337,11000,1830472,21439,149,1.0,2005,NaN,NaN,35NX2,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011
401122,6333338,11500,1887659,21439,149,1.0,2005,NaN,NaN,35NX2,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011
401123,6333341,9000,1903570,21435,149,2.0,2005,NaN,NaN,30NX,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011
401124,6333342,7750,1926965,21435,149,2.0,2005,NaN,NaN,30NX,...,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN,2011

### drop column with more than 75% of null values

In [ ]:
to_drop = null_columns[null_columns > 75].index
train_df.drop(columns = to_drop, inplace=True)
train_df

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,fiModelDesc,fiBaseModel,...,ProductGroupDesc,Drive_System,Enclosure,Forks,Ride_Control,Transmission,Hydraulics,Ripper,Coupler,saleYear
0,1139246,66000,999089,3157,121,3.0,2004,68.0,521D,521,...,Wheel Loader,NaN,EROPS w AC,None or Unspecified,None or Unspecified,NaN,2 Valve,NaN,None or Unspecified,2006
1,1139248,57000,117657,77,121,3.0,1996,4640.0,950FII,950,...,Wheel Loader,NaN,EROPS w AC,None or Unspecified,None or Unspecified,NaN,2 Valve,NaN,None or Unspecified,2004
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,226,226,...,Skid Steer Loaders,NaN,OROPS,None or Unspecified,NaN,NaN,Auxiliary,NaN,None or Unspecified,2004
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,PC120-6E,PC120,...,Track Excavators,NaN,EROPS w AC,NaN,NaN,NaN,2 Valve,NaN,None or Unspecified,2011
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,S175,S175,...,Skid Steer Loaders,NaN,EROPS,None or Unspecified,NaN,NaN,Auxiliary,NaN,None or Unspecified,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,NaN,35NX2,35,...,Track Excavators,NaN,EROPS,NaN,NaN,NaN,Auxiliary,NaN,None or Unspecified,2011
401121,6333337,11000,1830472,21439,149,1.0,2005,NaN,35NX2,35,...,Track Excavators,NaN,EROPS,NaN,NaN,NaN,Standard,NaN,None or Unspecified,2011
401122,6333338,11500,1887659,21439,149,1.0,2005,NaN,35NX2,35,...,Track Excavators,NaN,EROPS,NaN,NaN,NaN,Auxiliary,NaN,None or Unspecified,2011
401123,6333341,9000,1903570,21435,149,2.0,2005,NaN,30NX,30,...,Track Excavators,NaN,EROPS,NaN,NaN,NaN,Standard,NaN,None or Unspecified,2011
401124,6333342,7750,1926965,21435,149,2.0,2005,NaN,30NX,30,...,Track Excavators,NaN,EROPS,NaN,NaN,NaN,Standard,NaN,None or Unspecified,2011

### giving remaining null values appropriat values

In [ ]:
non_num_cols = train_df.select_dtypes(include='object').columns
num_cols = train_df.select_dtypes(include=['int64', 'float64', 'int32']).columns

for col in non_num_cols:
    train_df[col].fillna('Unknown', inplace=True)

for col in num_cols:
    train_df[col].fillna(train_df[col].median(), inplace=True)

final_missing = train_df.isnull().sum()
final_missing

<ipython-input-63-3997147075>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df[col].fillna('Unknown', inplace=True)
<ipython-input-63-3997147075>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df[col].fillna(train_df[col].median(), inplace=True)

SalesID                     0
SalePrice                   0
MachineID                   0
ModelID                     0
datasource                  0
auctioneerID                0
YearMade                    0
MachineHoursCurrentMeter    0
fiModelDesc                 0
fiBaseModel                 0
fiSecondaryDesc             0
ProductSize                 0
fiProductClassDesc          0
state                       0
ProductGroup                0
ProductGroupDesc            0
Drive_System                0
Enclosure                   0
Forks                       0
Ride_Control                0
Transmission                0
Hydraulics                  0
Ripper                      0
Coupler                     0
saleYear                    0
dtype: int64

In [ ]:
train_df
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   SalePrice                 401125 non-null  int64
 2   MachineID                 401125 non-null  int64
 3   ModelID                   401125 non-null  int64
 4   datasource                401125 non-null  int64
 5   auctioneerID              401125 non-null  float64
 6   YearMade                  401125 non-null  int64
 7   MachineHoursCurrentMeter  401125 non-null  float64
 8   fiModelDesc               401125 non-null  object
 9   fiBaseModel               401125 non-null  object
 10  fiSecondaryDesc           401125 non-null  object
 11  ProductSize               401125 non-null  object
 12  fiProductClassDesc        401125 non-null  object
 13  state                     401125 non-null  object
 14  ProductGroup              401125 non-null  object
 15  ProductGroupDesc          401125 non-null  object
 16  Drive_System              401125 non-null  object
 17  Enclosure                 401125 non-null  object
 18  Forks                     401125 non-null  object
 19  Ride_Control              401125 non-null  object
 20  Transmission              401125 non-null  object
 21  Hydraulics                401125 non-null  object
 22  Ripper                    401125 non-null  object
 23  Coupler                   401125 non-null  object
 24  saleYear                  401125 non-null  int32
dtypes: float64(2), int32(1), int64(6), object(16)
memory usage: 75.0+ MB

In [ ]:
train_df

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,fiModelDesc,fiBaseModel,...,ProductGroupDesc,Drive_System,Enclosure,Forks,Ride_Control,Transmission,Hydraulics,Ripper,Coupler,saleYear
0,1139246,66000,999089,3157,121,3.0,2004,68.0,521D,521,...,Wheel Loader,Unknown,EROPS w AC,None or Unspecified,None or Unspecified,Unknown,2 Valve,Unknown,None or Unspecified,2006
1,1139248,57000,117657,77,121,3.0,1996,4640.0,950FII,950,...,Wheel Loader,Unknown,EROPS w AC,None or Unspecified,None or Unspecified,Unknown,2 Valve,Unknown,None or Unspecified,2004
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,226,226,...,Skid Steer Loaders,Unknown,OROPS,None or Unspecified,Unknown,Unknown,Auxiliary,Unknown,None or Unspecified,2004
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,PC120-6E,PC120,...,Track Excavators,Unknown,EROPS w AC,Unknown,Unknown,Unknown,2 Valve,Unknown,None or Unspecified,2011
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,S175,S175,...,Skid Steer Loaders,Unknown,EROPS,None or Unspecified,Unknown,Unknown,Auxiliary,Unknown,None or Unspecified,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,0.0,35NX2,35,...,Track Excavators,Unknown,EROPS,Unknown,Unknown,Unknown,Auxiliary,Unknown,None or Unspecified,2011
401121,6333337,11000,1830472,21439,149,1.0,2005,0.0,35NX2,35,...,Track Excavators,Unknown,EROPS,Unknown,Unknown,Unknown,Standard,Unknown,None or Unspecified,2011
401122,6333338,11500,1887659,21439,149,1.0,2005,0.0,35NX2,35,...,Track Excavators,Unknown,EROPS,Unknown,Unknown,Unknown,Auxiliary,Unknown,None or Unspecified,2011
401123,6333341,9000,1903570,21435,149,2.0,2005,0.0,30NX,30,...,Track Excavators,Unknown,EROPS,Unknown,Unknown,Unknown,Standard,Unknown,None or Unspecified,2011
401124,6333342,7750,1926965,21435,149,2.0,2005,0.0,30NX,30,...,Track Excavators,Unknown,EROPS,Unknown,Unknown,Unknown,Standard,Unknown,None or Unspecified,2011

In [ ]:
cleaned_train_df = train_df.copy()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression

In [ ]:
cleaned_train_df['ModelID'] = cleaned_train_df['ModelID'].astype('category')
cleaned_train_df['auctioneerID'] = cleaned_train_df['auctioneerID'].astype('category')

In [ ]:
cleaned_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   SalePrice                 401125 non-null  int64
 2   MachineID                 401125 non-null  int64
 3   ModelID                   401125 non-null  category
 4   datasource                401125 non-null  int64
 5   auctioneerID              401125 non-null  category
 6   YearMade                  401125 non-null  int64
 7   MachineHoursCurrentMeter  401125 non-null  float64
 8   fiModelDesc               401125 non-null  object
 9   fiBaseModel               401125 non-null  object
 10  fiSecondaryDesc           401125 non-null  object
 11  ProductSize               401125 non-null  object
 12  fiProductClassDesc        401125 non-null  object
 13  state                     401125 non-null  object
 14  ProductGroup              401125 non-null  object
 15  ProductGroupDesc          401125 non-null  object
 16  Drive_System              401125 non-null  object
 17  Enclosure                 401125 non-null  object
 18  Forks                     401125 non-null  object
 19  Ride_Control              401125 non-null  object
 20  Transmission              401125 non-null  object
 21  Hydraulics                401125 non-null  object
 22  Ripper                    401125 non-null  object
 23  Coupler                   401125 non-null  object
 24  saleYear                  401125 non-null  int32
dtypes: category(2), float64(1), int32(1), int64(5), object(16)
memory usage: 70.2+ MB

In [ ]:
new_train_df = cleaned_train_df.drop(columns=['SalesID','MachineID','fiModelDesc','fiSecondaryDesc','fiProductClassDesc','ProductGroupDesc'])

In [ ]:
new_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalePrice                 401125 non-null  int64
 1   ModelID                   401125 non-null  category
 2   datasource                401125 non-null  int64
 3   auctioneerID              401125 non-null  category
 4   YearMade                  401125 non-null  int64
 5   MachineHoursCurrentMeter  401125 non-null  float64
 6   fiBaseModel               401125 non-null  object
 7   ProductSize               401125 non-null  object
 8   state                     401125 non-null  object
 9   ProductGroup              401125 non-null  object
 10  Drive_System              401125 non-null  object
 11  Enclosure                 401125 non-null  object
 12  Forks                     401125 non-null  object
 13  Ride_Control              401125 non-null  object
 14  Transmission              401125 non-null  object
 15  Hydraulics                401125 non-null  object
 16  Ripper                    401125 non-null  object
 17  Coupler                   401125 non-null  object
 18  saleYear                  401125 non-null  int32
dtypes: category(2), float64(1), int32(1), int64(3), object(12)
memory usage: 51.8+ MB

In [ ]:
new_train_df = cleaned_train_df.drop(columns=['ProductSize'])

In [ ]:
new_train_df.drop('Forks',axis=1,inplace=True)

In [ ]:
new_train_df['fiBaseModel'] = new_train_df['fiBaseModel'].astype('category')
new_train_df['state'] = new_train_df['state'].astype('category')
new_train_df['ProductGroup'] = new_train_df['ProductGroup'].astype('category')
new_train_df['Drive_System'] = new_train_df['Drive_System'].astype('category')
new_train_df['Enclosure'] = new_train_df['Enclosure'].astype('category')
new_train_df['Transmission'] = new_train_df['Transmission'].astype('category')

In [ ]:
new_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 23 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   SalePrice                 401125 non-null  int64
 2   MachineID                 401125 non-null  int64
 3   ModelID                   401125 non-null  category
 4   datasource                401125 non-null  int64
 5   auctioneerID              401125 non-null  category
 6   YearMade                  401125 non-null  int64
 7   MachineHoursCurrentMeter  401125 non-null  float64
 8   fiModelDesc               401125 non-null  object
 9   fiBaseModel               401125 non-null  category
 10  fiSecondaryDesc           401125 non-null  object
 11  fiProductClassDesc        401125 non-null  object
 12  state                     401125 non-null  category
 13  ProductGroup              401125 non-null  category
 14  ProductGroupDesc          401125 non-null  object
 15  Drive_System              401125 non-null  category
 16  Enclosure                 401125 non-null  category
 17  Ride_Control              401125 non-null  object
 18  Transmission              401125 non-null  category
 19  Hydraulics                401125 non-null  object
 20  Ripper                    401125 non-null  object
 21  Coupler                   401125 non-null  object
 22  saleYear                  401125 non-null  int32
dtypes: category(8), float64(1), int32(1), int64(5), object(8)
memory usage: 48.4+ MB

In [ ]:
new_train_df['saleYear'] = new_train_df['saleYear'].astype('int64')

In [ ]:
from sklearn.preprocessing import LabelEncoder
df_encoded = new_train_df.copy()

for col in df_encoded.select_dtypes(include=['category']).columns:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))

In [ ]:
cleaned_data_path = "/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/df_encoded.csv"
df_encoded.to_csv(cleaned_data_path, index=False)

In [ ]:
cleaned_data_path = "/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/df_encoded.csv"
df_encoded = pd.read_csv(cleaned_data_path)

In [ ]:
cleaned_data_path = "/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/Valid.csv"
df_valid = pd.read_csv(cleaned_data_path)

In [ ]:
cleaned_data_path = "/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/new_train_df.csv"
new_train_df = pd.read_csv(cleaned_data_path)

In [ ]:
X_train = df_encoded.drop(columns=['SalePrice'])
y_train = df_encoded['SalePrice']

In [ ]:
X_valid = [X_train.columns.intersection(df_valid.columns)]

In [ ]:
df_valid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11573 entries, 0 to 11572
Data columns (total 52 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SalesID                   11573 non-null  int64
 1   MachineID                 11573 non-null  int64
 2   ModelID                   11573 non-null  int64
 3   datasource                11573 non-null  int64
 4   auctioneerID              11573 non-null  int64
 5   YearMade                  11573 non-null  int64
 6   MachineHoursCurrentMeter  4739 non-null   float64
 7   UsageBand                 4031 non-null   object
 8   saledate                  11573 non-null  object
 9   fiModelDesc               11573 non-null  object
 10  fiBaseModel               11573 non-null  object
 11  fiSecondaryDesc           8037 non-null   object
 12  fiModelSeries             1759 non-null   object
 13  fiModelDescriptor         2897 non-null   object
 14  ProductSize               5743 non-null   object
 15  fiProductClassDesc        11573 non-null  object
 16  state                     11573 non-null  object
 17  ProductGroup              11573 non-null  object
 18  ProductGroupDesc          11573 non-null  object
 19  Drive_System              2726 non-null   object
 20  Enclosure                 11564 non-null  object
 21  Forks                     5638 non-null   object
 22  Pad_Type                  1962 non-null   object
 23  Ride_Control              4122 non-null   object
 24  Stick                     1962 non-null   object
 25  Transmission              4777 non-null   object
 26  Turbocharged              1962 non-null   object
 27  Blade_Extension           764 non-null    object
 28  Blade_Width               764 non-null    object
 29  Enclosure_Type            764 non-null    object
 30  Engine_Horsepower         764 non-null    object
 31  Hydraulics                9563 non-null   object
 32  Pushblock                 764 non-null    object
 33  Ripper                    2808 non-null   object
 34  Scarifier                 764 non-null    object
 35  Tip_Control               764 non-null    object
 36  Tire_Size                 2920 non-null   object
 37  Coupler                   6727 non-null   object
 38  Coupler_System            1516 non-null   object
 39  Grouser_Tracks            1513 non-null   object
 40  Hydraulics_Flow           1513 non-null   object
 41  Track_Type                3040 non-null   object
 42  Undercarriage_Pad_Width   3044 non-null   object
 43  Stick_Length              3043 non-null   object
 44  Thumb                     3044 non-null   object
 45  Pattern_Changer           3043 non-null   object
 46  Grouser_Type              3040 non-null   object
 47  Backhoe_Mounting          2040 non-null   object
 48  Blade_Type                2042 non-null   object
 49  Travel_Controls           2043 non-null   object
 50  Differential_Type         2153 non-null   object
 51  Steering_Controls         2153 non-null   object
dtypes: float64(1), int64(6), object(45)
memory usage: 4.6+ MB

In [ ]:

common_cols = df_encoded.columns.intersection(df_valid.columns)


df_encoded_common = df_encoded[common_cols]
df_valid_common = df_valid[common_cols]

In [ ]:
df_valid_common.info()
df_encoded_common.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11573 entries, 0 to 11572
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SalesID                   11573 non-null  int64
 1   MachineID                 11573 non-null  int64
 2   ModelID                   11573 non-null  int64
 3   datasource                11573 non-null  int64
 4   auctioneerID              11573 non-null  int64
 5   YearMade                  11573 non-null  int64
 6   MachineHoursCurrentMeter  4739 non-null   float64
 7   fiModelDesc               11573 non-null  object
 8   fiBaseModel               11573 non-null  object
 9   fiSecondaryDesc           8037 non-null   object
 10  fiProductClassDesc        11573 non-null  object
 11  state                     11573 non-null  object
 12  ProductGroup              11573 non-null  object
 13  ProductGroupDesc          11573 non-null  object
 14  Drive_System              2726 non-null   object
 15  Enclosure                 11564 non-null  object
 16  Ride_Control              4122 non-null   object
 17  Transmission              4777 non-null   object
 18  Hydraulics                9563 non-null   object
 19  Ripper                    2808 non-null   object
 20  Coupler                   6727 non-null   object
dtypes: float64(1), int64(6), object(14)
memory usage: 1.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 21 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   MachineID                 401125 non-null  int64
 2   ModelID                   401125 non-null  int64
 3   datasource                401125 non-null  int64
 4   auctioneerID              401125 non-null  int64
 5   YearMade                  401125 non-null  int64
 6   MachineHoursCurrentMeter  401125 non-null  float64
 7   fiModelDesc               401125 non-null  object
 8   fiBaseModel               401125 non-null  int64
 9   fiSecondaryDesc           401125 non-null  object
 10  fiProductClassDesc        401125 non-null  object
 11  state                     401125 non-null  int64
 12  ProductGroup              401125 non-null  int64
 13  ProductGroupDesc          401125 non-null  object
 14  Drive_System              401125 non-null  int64
 15  Enclosure                 401125 non-null  int64
 16  Ride_Control              401125 non-null  object
 17  Transmission              401125 non-null  int64
 18  Hydraulics                401125 non-null  object
 19  Ripper                    401125 non-null  object
 20  Coupler                   401125 non-null  object
dtypes: float64(1), int64(12), object(8)
memory usage: 64.3+ MB

In [ ]:
df_valid_common['ModelID'] = df_valid_common['ModelID'].astype('category')
df_valid_common['auctioneerID'] = df_valid_common['auctioneerID'].astype('category')
df_valid_common['fiBaseModel'] = df_valid_common['fiBaseModel'].astype('category')
df_valid_common['state'] = df_valid_common['state'].astype('category')
df_valid_common['ProductGroup'] = df_valid_common['ProductGroup'].astype('category')
df_valid_common['Drive_System'] = df_valid_common['Drive_System'].astype('category')
df_valid_common['Enclosure'] = df_valid_common['Enclosure'].astype('category')
df_valid_common['Transmission'] = df_valid_common['Transmission'].astype('category')

<ipython-input-28-1621160086>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common['ModelID'] = df_valid_common['ModelID'].astype('category')
<ipython-input-28-1621160086>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common['auctioneerID'] = df_valid_common['auctioneerID'].astype('category')
<ipython-input-28-1621160086>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common['fiBaseModel'] = df_valid_common['fiBaseModel'].astype('category')
<ipython-input-28-1621160086>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common['state'] = df_valid_common['state'].astype('category')
<ipython-input-28-1621160086>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common['ProductGroup'] = df_valid_common['ProductGroup'].astype('category')
<ipython-input-28-1621160086>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common['Drive_System'] = df_valid_common['Drive_System'].astype('category')
<ipython-input-28-1621160086>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common['Enclosure'] = df_valid_common['Enclosure'].astype('category')
<ipython-input-28-1621160086>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common['Transmission'] = df_valid_common['Transmission'].astype('category')

In [ ]:
df_valid_common.info()
df_encoded_common.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11573 entries, 0 to 11572
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SalesID                   11573 non-null  int64
 1   MachineID                 11573 non-null  int64
 2   ModelID                   11573 non-null  category
 3   datasource                11573 non-null  int64
 4   auctioneerID              11573 non-null  category
 5   YearMade                  11573 non-null  int64
 6   MachineHoursCurrentMeter  4739 non-null   float64
 7   fiModelDesc               11573 non-null  object
 8   fiBaseModel               11573 non-null  category
 9   fiSecondaryDesc           8037 non-null   object
 10  fiProductClassDesc        11573 non-null  object
 11  state                     11573 non-null  category
 12  ProductGroup              11573 non-null  category
 13  ProductGroupDesc          11573 non-null  object
 14  Drive_System              2726 non-null   category
 15  Enclosure                 11564 non-null  category
 16  Ride_Control              4122 non-null   object
 17  Transmission              4777 non-null   category
 18  Hydraulics                9563 non-null   object
 19  Ripper                    2808 non-null   object
 20  Coupler                   6727 non-null   object
dtypes: category(8), float64(1), int64(4), object(8)
memory usage: 1.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 21 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   MachineID                 401125 non-null  int64
 2   ModelID                   401125 non-null  int64
 3   datasource                401125 non-null  int64
 4   auctioneerID              401125 non-null  int64
 5   YearMade                  401125 non-null  int64
 6   MachineHoursCurrentMeter  401125 non-null  float64
 7   fiModelDesc               401125 non-null  object
 8   fiBaseModel               401125 non-null  int64
 9   fiSecondaryDesc           401125 non-null  object
 10  fiProductClassDesc        401125 non-null  object
 11  state                     401125 non-null  int64
 12  ProductGroup              401125 non-null  int64
 13  ProductGroupDesc          401125 non-null  object
 14  Drive_System              401125 non-null  int64
 15  Enclosure                 401125 non-null  int64
 16  Ride_Control              401125 non-null  object
 17  Transmission              401125 non-null  int64
 18  Hydraulics                401125 non-null  object
 19  Ripper                    401125 non-null  object
 20  Coupler                   401125 non-null  object
dtypes: float64(1), int64(12), object(8)
memory usage: 64.3+ MB

In [ ]:
from sklearn.preprocessing import LabelEncoder

for col in df_valid_common.select_dtypes(include=['category']).columns:
    le = LabelEncoder()
    df_valid_common[col] = le.fit_transform(df_valid_common[col].astype(str))

<ipython-input-31-1847012269>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common[col] = le.fit_transform(df_valid_common[col].astype(str))
<ipython-input-31-1847012269>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common[col] = le.fit_transform(df_valid_common[col].astype(str))
<ipython-input-31-1847012269>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common[col] = le.fit_transform(df_valid_common[col].astype(str))
<ipython-input-31-1847012269>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common[col] = le.fit_transform(df_valid_common[col].astype(str))
<ipython-input-31-1847012269>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common[col] = le.fit_transform(df_valid_common[col].astype(str))
<ipython-input-31-1847012269>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common[col] = le.fit_transform(df_valid_common[col].astype(str))
<ipython-input-31-1847012269>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common[col] = le.fit_transform(df_valid_common[col].astype(str))
<ipython-input-31-1847012269>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common[col] = le.fit_transform(df_valid_common[col].astype(str))

In [ ]:
df_valid_common.info()
df_encoded_common.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11573 entries, 0 to 11572
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SalesID                   11573 non-null  int64
 1   MachineID                 11573 non-null  int64
 2   ModelID                   11573 non-null  int64
 3   datasource                11573 non-null  int64
 4   auctioneerID              11573 non-null  int64
 5   YearMade                  11573 non-null  int64
 6   MachineHoursCurrentMeter  4739 non-null   float64
 7   fiModelDesc               11573 non-null  object
 8   fiBaseModel               11573 non-null  int64
 9   fiSecondaryDesc           8037 non-null   object
 10  fiProductClassDesc        11573 non-null  object
 11  state                     11573 non-null  int64
 12  ProductGroup              11573 non-null  int64
 13  ProductGroupDesc          11573 non-null  object
 14  Drive_System              11573 non-null  int64
 15  Enclosure                 11573 non-null  int64
 16  Ride_Control              4122 non-null   object
 17  Transmission              11573 non-null  int64
 18  Hydraulics                9563 non-null   object
 19  Ripper                    2808 non-null   object
 20  Coupler                   6727 non-null   object
dtypes: float64(1), int64(12), object(8)
memory usage: 1.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 21 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   MachineID                 401125 non-null  int64
 2   ModelID                   401125 non-null  int64
 3   datasource                401125 non-null  int64
 4   auctioneerID              401125 non-null  int64
 5   YearMade                  401125 non-null  int64
 6   MachineHoursCurrentMeter  401125 non-null  float64
 7   fiModelDesc               401125 non-null  object
 8   fiBaseModel               401125 non-null  int64
 9   fiSecondaryDesc           401125 non-null  object
 10  fiProductClassDesc        401125 non-null  object
 11  state                     401125 non-null  int64
 12  ProductGroup              401125 non-null  int64
 13  ProductGroupDesc          401125 non-null  object
 14  Drive_System              401125 non-null  int64
 15  Enclosure                 401125 non-null  int64
 16  Ride_Control              401125 non-null  object
 17  Transmission              401125 non-null  int64
 18  Hydraulics                401125 non-null  object
 19  Ripper                    401125 non-null  object
 20  Coupler                   401125 non-null  object
dtypes: float64(1), int64(12), object(8)
memory usage: 64.3+ MB

In [ ]:
X_train.info()
y_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   MachineID                 401125 non-null  int64
 2   ModelID                   401125 non-null  int64
 3   datasource                401125 non-null  int64
 4   auctioneerID              401125 non-null  int64
 5   YearMade                  401125 non-null  int64
 6   MachineHoursCurrentMeter  401125 non-null  float64
 7   fiModelDesc               401125 non-null  object
 8   fiBaseModel               401125 non-null  int64
 9   fiSecondaryDesc           401125 non-null  object
 10  fiProductClassDesc        401125 non-null  object
 11  state                     401125 non-null  int64
 12  ProductGroup              401125 non-null  int64
 13  ProductGroupDesc          401125 non-null  object
 14  Drive_System              401125 non-null  int64
 15  Enclosure                 401125 non-null  int64
 16  Ride_Control              401125 non-null  object
 17  Transmission              401125 non-null  int64
 18  Hydraulics                401125 non-null  object
 19  Ripper                    401125 non-null  object
 20  Coupler                   401125 non-null  object
 21  saleYear                  401125 non-null  int64
dtypes: float64(1), int64(13), object(8)
memory usage: 67.3+ MB
<class 'pandas.core.series.Series'>
RangeIndex: 401125 entries, 0 to 401124
Series name: SalePrice
Non-Null Count   Dtype
--------------   -----
401125 non-null  int64
dtypes: int64(1)
memory usage: 3.1 MB

In [ ]:
y_train = df_encoded['SalePrice']

In [ ]:
y_train

0         66000
1         57000
2         10000
3         38500
4         11000
          ...
401120    10500
401121    11000
401122    11500
401123     9000
401124     7750
Name: SalePrice, Length: 401125, dtype: int64

In [ ]:
X_valid = df_valid_common

In [ ]:
X_valid

,SalesID,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,fiModelDesc,fiBaseModel,fiSecondaryDesc,...,state,ProductGroup,ProductGroupDesc,Drive_System,Enclosure,Ride_Control,Transmission,Hydraulics,Ripper,Coupler
0,1222837,902859,210,121,9,1000,0.0,375L,121,NaN,...,14,3,Track Excavators,4,0,NaN,7,Standard,NaN,None or Unspecified
1,1222839,1048320,1186,121,9,2006,4412.0,TX300LC2,727,LC,...,5,3,Track Excavators,4,2,NaN,7,Auxiliary,NaN,Hydraulic
2,1222841,999308,1314,121,9,2000,10127.0,270LC,74,NaN,...,5,3,Track Excavators,4,2,NaN,7,Auxiliary,NaN,None or Unspecified
3,1222843,1062425,675,121,9,1000,4682.0,892DLC,247,D,...,5,3,Track Excavators,4,0,NaN,7,Standard,NaN,None or Unspecified
4,1222845,1032841,1356,121,9,2002,8150.0,544H,155,H,...,7,5,Wheel Loader,4,2,None or Unspecified,7,2 Valve,NaN,Manual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11568,6333344,1919201,721,149,7,2005,NaN,30NX,82,NX,...,41,3,Track Excavators,4,0,NaN,7,Standard,NaN,None or Unspecified
11569,6333345,1882122,722,149,7,2005,NaN,30NX2,82,NX,...,7,3,Track Excavators,4,0,NaN,7,Auxiliary,NaN,None or Unspecified
11570,6333347,1944213,721,149,7,2005,NaN,30NX,82,NX,...,7,3,Track Excavators,4,0,NaN,7,Auxiliary,NaN,None or Unspecified
11571,6333348,1794518,721,149,7,2006,NaN,30NX,82,NX,...,41,3,Track Excavators,4,0,NaN,7,Auxiliary,NaN,None or Unspecified
11572,6333349,1944743,722,149,7,2006,NaN,30NX2,82,NX,...,7,3,Track Excavators,4,0,NaN,7,Auxiliary,NaN,None or Unspecified

In [ ]:
categorical_cols = X_train.select_dtypes(include='object').columns.tolist()
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_train[categorical_cols] = encoder.fit_transform(X_train[categorical_cols])
X_valid[categorical_cols] = encoder.transform(X_valid[categorical_cols])

<ipython-input-43-2883077720>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid[categorical_cols] = encoder.transform(X_valid[categorical_cols])

In [ ]:
X_train.info()
y_train.info()
X_valid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   MachineID                 401125 non-null  int64
 2   ModelID                   401125 non-null  int64
 3   datasource                401125 non-null  int64
 4   auctioneerID              401125 non-null  int64
 5   YearMade                  401125 non-null  int64
 6   MachineHoursCurrentMeter  401125 non-null  float64
 7   fiModelDesc               401125 non-null  float64
 8   fiBaseModel               401125 non-null  int64
 9   fiSecondaryDesc           401125 non-null  float64
 10  fiProductClassDesc        401125 non-null  float64
 11  state                     401125 non-null  int64
 12  ProductGroup              401125 non-null  int64
 13  ProductGroupDesc          401125 non-null  float64
 14  Drive_System              401125 non-null  int64
 15  Enclosure                 401125 non-null  int64
 16  Ride_Control              401125 non-null  float64
 17  Transmission              401125 non-null  int64
 18  Hydraulics                401125 non-null  float64
 19  Ripper                    401125 non-null  float64
 20  Coupler                   401125 non-null  float64
 21  saleYear                  401125 non-null  int64
dtypes: float64(9), int64(13)
memory usage: 67.3 MB
<class 'pandas.core.series.Series'>
RangeIndex: 401125 entries, 0 to 401124
Series name: SalePrice
Non-Null Count   Dtype
--------------   -----
401125 non-null  int64
dtypes: int64(1)
memory usage: 3.1 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11573 entries, 0 to 11572
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SalesID                   11573 non-null  int64
 1   MachineID                 11573 non-null  int64
 2   ModelID                   11573 non-null  int64
 3   datasource                11573 non-null  int64
 4   auctioneerID              11573 non-null  int64
 5   YearMade                  11573 non-null  int64
 6   MachineHoursCurrentMeter  4739 non-null   float64
 7   fiModelDesc               11573 non-null  float64
 8   fiBaseModel               11573 non-null  int64
 9   fiSecondaryDesc           11573 non-null  float64
 10  fiProductClassDesc        11573 non-null  float64
 11  state                     11573 non-null  int64
 12  ProductGroup              11573 non-null  int64
 13  ProductGroupDesc          11573 non-null  float64
 14  Drive_System              11573 non-null  int64
 15  Enclosure                 11573 non-null  int64
 16  Ride_Control              11573 non-null  float64
 17  Transmission              11573 non-null  int64
 18  Hydraulics                11573 non-null  float64
 19  Ripper                    11573 non-null  float64
 20  Coupler                   11573 non-null  float64
dtypes: float64(9), int64(12)
memory usage: 1.9 MB

In [ ]:
df_valid['saledate'] = pd.to_datetime(df_valid['saledate'])
df_valid['saleYear'] = df_valid['saledate'].dt.year
df_valid.drop('saledate', axis=1, inplace=True)

In [ ]:
df_valid_common['saleYear'] = df_valid['saleYear']

<ipython-input-54-257479625>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid_common['saleYear'] = df_valid['saleYear']

In [ ]:
X_valid = df_valid_common

In [ ]:
X_valid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11573 entries, 0 to 11572
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SalesID                   11573 non-null  int64
 1   MachineID                 11573 non-null  int64
 2   ModelID                   11573 non-null  int64
 3   datasource                11573 non-null  int64
 4   auctioneerID              11573 non-null  int64
 5   YearMade                  11573 non-null  int64
 6   MachineHoursCurrentMeter  4739 non-null   float64
 7   fiModelDesc               11573 non-null  float64
 8   fiBaseModel               11573 non-null  int64
 9   fiSecondaryDesc           11573 non-null  float64
 10  fiProductClassDesc        11573 non-null  float64
 11  state                     11573 non-null  int64
 12  ProductGroup              11573 non-null  int64
 13  ProductGroupDesc          11573 non-null  float64
 14  Drive_System              11573 non-null  int64
 15  Enclosure                 11573 non-null  int64
 16  Ride_Control              11573 non-null  float64
 17  Transmission              11573 non-null  int64
 18  Hydraulics                11573 non-null  float64
 19  Ripper                    11573 non-null  float64
 20  Coupler                   11573 non-null  float64
 21  saleYear                  11573 non-null  int32
dtypes: float64(9), int32(1), int64(12)
memory usage: 1.9 MB

In [ ]:
X_valid['MachineHoursCurrentMeter'].fillna(X_valid['MachineHoursCurrentMeter'].median(), inplace=True)

<ipython-input-59-1730586209>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_valid['MachineHoursCurrentMeter'].fillna(X_valid['MachineHoursCurrentMeter'].median(), inplace=True)
<ipython-input-59-1730586209>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['MachineHoursCurrentMeter'].fillna(X_valid['MachineHoursCurrentMeter'].median(), inplace=True)

In [ ]:
cleaned_data_path = "/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/random_forest_benchmark_test.csv"
df_random_forest = pd.read_csv(cleaned_data_path)

In [ ]:
from sklearn.model_selection import train_test_split

X = X_train
y = y_train

# Split into training (80%) and test (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
models = {
    'LinearRegression': LinearRegression(),
    'RandomForest': RandomForestRegressor(n_jobs=-1, random_state=42),
    'GradientBoosting': GradientBoostingRegressor(random_state=42)
}

for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    mse = mean_squared_error(y_test, preds)
    rmse = np.sqrt(mse)  # manual RMSE
    r2 = r2_score(y_test, preds)
    print(f"{name}: RMSE = {rmse:.2f}, R² = {r2:.4f}")

LinearRegression: RMSE = 19459.53, R² = 0.2757
RandomForest: RMSE = 7485.30, R² = 0.8928
GradientBoosting: RMSE = 12547.93, R² = 0.6988

In [ ]:
cleaned_data_path = "/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/Test.csv"
test = pd.read_csv(cleaned_data_path)

In [ ]:
test['saledate'] = pd.to_datetime(test['saledate'])
test['saleYear'] = test['saledate'].dt.year
sales_ids = test['SalesID']
X_test_final = test[X_train.columns.intersection(test.columns)].copy()

for col in X_test_final.select_dtypes(include='object').columns:
    X_test_final[col] = X_test_final[col].fillna('Unknown')
for col in X_test_final.select_dtypes(include=['int64', 'float64']).columns:
    X_test_final[col] = X_test_final[col].fillna(X_test_final[col].median())

categorical_cols = X_test_final.select_dtypes(include='object').columns.tolist()
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_test_final[categorical_cols] = encoder.fit_transform(X_test_final[categorical_cols])

In [ ]:
model = RandomForestRegressor(n_jobs=1, random_state=50)
model.fit(X_train, y_train)

RandomForestRegressor(n_jobs=1, random_state=50)

In [73]:
preds = model.predict(X_test_final)
submission = pd.DataFrame({'SalesID': sales_ids, 'SalePrice': preds})
submission.to_csv('test_predictions.csv', index=False)

In [76]:
submission

       SalesID  SalePrice
0      1227829    22073.0
1      1227844    23927.0
2      1227847    11335.0
3      1227848    54490.0
4      1227863    49325.0
...        ...        ...
12452  6643171    11477.5
12453  6643173     9882.5
12454  6643184    18592.5
12455  6643186    10980.0
12456  6643196    11547.5

[12457 rows x 2 columns]

In [77]:
cleaned_data_path = "/content/drive/MyDrive/Deepflow/major assignmnet 1/datasheet/bluebook-for-bulldozers/submission.csv"
submission.to_csv(cleaned_data_path, index=False)